### ISSUE TITLE
Allow configuring/disabling additional mappings

### ISSUE THREAD

**Issue by kristijanhusak** [b3nj5m1n/kommentary#14]
Hi, I noticed you introduced additional mappings for increase/decrease.

I would like to be able to configure them or disable them, because my default mapping for commenting code is `<leader>c`, which I map to `gc`/`gcc` respectively. Issue is that these additional mappings cause my mapping to wait for timeout because there are mappings that are potentially pending. I tried using `nowait` but without luck.

**Comment by b3nj5m1n** [comment]
Yeah, this has been on my todo list for a while, my current plan is to provide a function in config called something like `use_extended_mappings` which will map all the `<leader>` commands, then anyone who wants those mappings can just call that function. I should have a patch in about an hour or so.

**Comment by b3nj5m1n** [comment]
Implemented with 5ae2485f66dd7caddba163bcdc6bdac3a4a40b96, if you could let quickly let me know if everything is working as you would expect, that would be great!

**Comment by kristijanhusak** [comment]
Works fine, thanks!
