### ISSUE TITLE
use_consistent_indentation option not working

### ISSUE THREAD

**Issue by metalelf0** [b3nj5m1n/kommentary#15]
Hi! First of all thanks for this plugin.

I was trying it out and I have an issue. I tried setting the `use_consistent_indentation` option to true. Here is my config:

```lua
local paq = require('paq-nvim').paq

paq {'b3nj5m1n/kommentary'}

require('kommentary.config').configure_language("default", {
    use_consistent_indentation = true,
})
```

However, when I try commenting out ruby code, I still get unindented comment chars:

```ruby
# Original code

class MyClass
  def initialize(args)
  end

  private
    
    def some_method
    end
end

# Expected result

# class MyClass
#   def initialize(args)
#   end
# 
#   private
#     
#     def some_method
#     end
# end

# Actual result

# class MyClass
  # def initialize(args)
  # end
#
  # private
#
    # def some_method
    # end
# end
```

Am I doing anything wrong?

Thanks, all the best!

**Comment by b3nj5m1n** [comment]
@metalelf0 You're absolutely right, I'm very sorry, that's due to a stupid mistake on my part that I missed in a refactor, thanks for making me aware. I'll fix it as soon as possible.

**Comment by b3nj5m1n** [comment]
Should hopefully be fixed with e93171ab548599a102d4f340ac9a50b29a26c018, if you could test it out @metalelf0 and let me know if it's working for you, that'd be great.

**Comment by metalelf0** [comment]
Haha man, that's great! I can confirm it works. Thanks a lot for your awesome work!

**Comment by b3nj5m1n** [comment]
> Haha man, that's great! I can confirm it works.

That's great to hear!

> Thanks a lot for your awesome work!

Thanks, I really appreicate it.
