### ISSUE TITLE
Can't figure out how to comment lines using custom mapping

### ISSUE THREAD

**Issue by beauwilliams** [b3nj5m1n/kommentary#16]
For example, I used to call my own commenting function using :ToggleComment()

I can not seem to figure out how to do so with kommentary so in the meantime I am still using my own plugin

I would like to use this mapping `nnoremap <silent>++ :call ToggleComment()<CR>`

But instead call kommentary 

Note, ++ is mapped to cmd+/ in my terminal, a shortcut I am accustomed to.

Sure its something simple but could not figure out how to do this after looking at the code. Thanks!

**Comment by b3nj5m1n** [comment]
Hi, if I understand correctly, you want to toggle the line you're currently on using ++?

This is how you would do it in lua:
```lua
vim.api.nvim_set_keymap('n', '++', '<Plug>kommentary_line_default', { silent = true })
```

In case you also want to have this mapping for visual mode and lines, here's how you would do that (A single + triggers these, adjust them to your needs):
```lua
vim.api.nvim_set_keymap('n', '+', '<Plug>kommentary_motion_default', { silent = true })
vim.api.nvim_set_keymap('v', '+', '<Plug>kommentary_visual_default', { silent = true })
```

And for good measure, the whole thing in vimscript:
```vim
nmap <silent>++ <Plug>kommentary_line_default
nmap <silent>+ <Plug>kommentary_motion_default
vmap <silent>+ <Plug>kommentary_visual_default
```

**Comment by beauwilliams** [comment]
Look this is my bad, I kept getting an error many times when I tried using that command `<Plug>kommentary_line_default` earlier. Must have been a silly typo or something. Your suggestion works perfect. Thanks!
