### ISSUE TITLE
Exit visual mode after toggling comment

### ISSUE THREAD

**Issue by elianiva** [b3nj5m1n/kommentary#20]
Hi there! Thanks for this plugin, I really like it. I have one issue though, how do I exit insert mode after toggling the comment? The current behaviour is after I toggle the comment, it stays in visual mode and I have to go back to normal mode manually. Is there a way to do this automatically?

**Comment by b3nj5m1n** [comment]
Hi, you can do this by remapping the default mappings, put this in your init.lua before you load the plugin:
```lua
vim.g.kommentary_create_default_mappings = false
```
And this after you've loaded the plugin:
```lua
vim.api.nvim_set_keymap("n", "gcc", "<Plug>kommentary_line_default", {})
vim.api.nvim_set_keymap("n", "gc", "<Plug>kommentary_motion_default", {})
vim.api.nvim_set_keymap("v", "gc", "<Plug>kommentary_visual_default<C-c>", {})
```
The `<C-c>` will press Control + c at the end of the mapping, thereby exiting visual mode.

**Comment by elianiva** [comment]
ah, thank you!

**Comment by alexanderjeurissen** [comment]
@b3nj5m1n Is there any reason for this not being the default behavior ?

**Comment by b3nj5m1n** [comment]
@alexanderjeurissen I personally like it better this way. I don't know if the majority of people feel like that though.

**Comment by paniash** [comment]
First of all, thanks for making a lua plugin as a replacement for vim-commentary.

> @alexanderjeurissen I personally like it better this way. I don't know if the majority of people feel like that though.

I feel that the majority of people who use this plugin are tpope refugees and would prefer the latter option (me being one of them).

**Comment by adrian5** [comment]
If this is a common enough query, giving it a brief mention in the [Configuration](https://github.com/b3nj5m1n/kommentary#configuration) section might be useful. I didn't expect the behavior either and went looking here.
