### ISSUE TITLE
question: mixing multiline and normal comments breaks plugin

### ISSUE THREAD

**Issue by matu3ba** [b3nj5m1n/kommentary#24]
Example code:
```cpp
  //for (std::pair<int, std::tuple<std::shared_ptr<Statement>, int, std::shared_ptr<Statement>, int>> e: edges)
  //  dbgEdge(e);
  /* for (std::pair<int, std::tuple<int, std::weak_ptr<Statement>>> e : incomingEdges)
    dbgincomingEdge(e);
  for (std::pair<int, std::tuple<int, std::shared_ptr<Statement>>> e : outgogingEdges)
    dbgoutgoingEdge(e); */
```

result on using `:gc`:
```cp
  /* //for (std::pair<int, std::tuple<std::shared_ptr<Statement>, int, std::shared_ptr<Statement>, int>> e: edges)
  //  dbgEdge(e);
  /* for (std::pair<int, std::tuple<int, std::weak_ptr<Statement>>> e : incomingEdges)
    dbgincomingEdge(e);
  for (std::pair<int, std::tuple<int, std::shared_ptr<Statement>>> e : outgogingEdges)
    dbgoutgoingEdge(e); */ */
```

**Comment by b3nj5m1n** [comment]
What did you type after gc? On what range are you trying to operate? And what is your desired behaviour?

**Comment by matu3ba** [comment]
Line selection of the full text. I do only press `gc`. It toggles back, when I press it again.

**Comment by b3nj5m1n** [comment]
Ok, what is your desired behaviour?

**Comment by matu3ba** [comment]
```cp
  for (std::pair<int, std::tuple<std::shared_ptr<Statement>, int, std::shared_ptr<Statement>, int>> e: edges)
    dbgEdge(e);
   for (std::pair<int, std::tuple<int, std::weak_ptr<Statement>>> e : incomingEdges)
    dbgincomingEdge(e);
  for (std::pair<int, std::tuple<int, std::shared_ptr<Statement>>> e : outgogingEdges)
    dbgoutgoingEdge(e);
```
and when I press again (everythin is still marked)
```cp
  /* for (std::pair<int, std::tuple<std::shared_ptr<Statement>, int, std::shared_ptr<Statement>, int>> e: edges)
    dbgEdge(e);
   for (std::pair<int, std::tuple<int, std::weak_ptr<Statement>>> e : incomingEdges)
    dbgincomingEdge(e);
  for (std::pair<int, std::tuple<int, std::shared_ptr<Statement>>> e : outgogingEdges)
    dbgoutgoingEdge(e); */
```

**Comment by b3nj5m1n** [comment]
You have several types of comments, if you want to uncomment them you need to do it individually. You can also use the extended mappings to reduce the comment level, which will ensure that you don't add a comment you don't want. Still, you'll have to uncomment the multi-line comment individually.

**Comment by matu3ba** [comment]
Is there a jump label to go to the beginning and end of comment block?

**Comment by b3nj5m1n** [comment]
There currently isn't any such functionality, the plugin will only find a multi-line comment if it is the exact range you're operating on. I have thought about implementing functionality for finding nested multi-line comments, which would enable you to uncomment everything in your original example without having to reselect, however I haven't yet gotten around to implementing it.

You could probably write a function pretty easily which would find the nearest start/end of a multi-line comment and jump to it though.

I'm not sure if/when I will implement the sort of nested-comment functionality, I'm very much open to pull requests though.

**Comment by matu3ba** [comment]
@b3nj5m1n The most efficient way would be to get the information from treesitter.

Thinking about it, nested-comment functionality could break all the weird stuff people write to generate documentation (which basically parses comments. This leads to semantical analysis, what a comment above a function or struct etc might mean.

**Comment by b3nj5m1n** [comment]
> The most efficient way would be to get the information from treesitter.

Not only the most efficient way, but the only realistic way to do this. Otherwise, to make sure the correct matching comments would be picked, we'd have to scan the entire buffer each time, which would be a waste of resources, and writing it to be incremental would be way too complicated.

I basically have 0 experience with treesitter, so I won't implement this, but as always I'm open to PRs.
