### ISSUE TITLE
Feature Suggestion: Styling for special comments. 

### ISSUE THREAD

**Issue by Chaitanyabsprip** [b3nj5m1n/kommentary#25]
It would be great to have VS Code's Better Comment like highlighting for TODO, XXX, etc comments and also the ones that have special characters, for example (python)`#! Something important` would be highlighted in red instead of normal gray for comments. I understand that this is not a mainline feature for a commenting plugin but it would be a niice integration. It would be a step towards being one stop plugin for multiple comments related plugin.

**Comment by b3nj5m1n** [comment]
Sorry, but I have to agree with the

> I understand that this is not a mainline feature for a commenting plugin

This isn't something in the scope of this plugin, maybe you should take a look at something like [this](https://github.com/stsewd/tree-sitter-comment).
