### ISSUE TITLE
[Bug] <Plug> mappings from README.md not working

### ISSUE THREAD

**Issue by kunzaatko** [b3nj5m1n/kommentary#35]
The mappings to `<Plug>kommentary_..._default` are not working:
```lua
         require'utils'.map('n', '<leader>kk', '<Plug>kommentary_line_default',
                           {noremap = true}) -- default style comment
        require'utils'.map('v', '<leader>kk', '<Plug>kommentary_visual_default',
                           {noremap = true}) -- default style
        require'utils'.map('n', '<leader>k', '<Plug>kommentary_motion_default',
                           {noremap = true}) -- default style
```

**Comment by b3nj5m1n** [comment]
Are you skipping the creation of the default mapping with `vim.g.kommentary_create_default_mappings = false`?

**Comment by kunzaatko** [comment]
That is what I have done with the `setup` key in packer, so everything was setup right. The problem was, that I forgot to execute `PackerClean`, so the plugin was still in my `start` folder and the command was never executed. Sorry for this mistake. It is working fine now. Thank you for your help!
