### ISSUE TITLE
Consider adding support for react and jsx files

### ISSUE THREAD

**Issue by ChristianChiarulli** [b3nj5m1n/kommentary#37]

**Comment by ChristianChiarulli** [comment]
Nvm seems like I should be able to do something like this:

```
require('kommentary.config').configure_language("rust", {
    single_line_comment_string = "//",
    multi_line_comment_strings = {"/*", "*/"},
})
```

**Comment by ChristianChiarulli** [comment]
I came up with something like this:

```
require('kommentary.config').configure_language("javascriptreact", {
    prefer_single_line_comments = true,
    single_line_comment_string = "{/*<commented line>*/}",
})
```

but I need to fill something in for `<commented line>`

**Comment by b3nj5m1n** [comment]
I'm not quite sure what it is you're trying to archieve, if you're talking about jsx support in general that's been discussed in #11, otherwise some clarification would be great.
