### ISSUE TITLE
Error on install and loading kommentary -- attempt to index field 'g' (a nil value)

### ISSUE THREAD

**Issue by richardmcsong** [b3nj5m1n/kommentary#38]
On a fresh install through vim-plug, I get this error when starting neovim:
```
E5105: Error while calling lua chunk: .../rsong/.vim/plugged/kommentary/lua/kommentary/config.lua:112: attempt to index field 'g' (a nil value)
```
I tried looking into it, but I'm not sure why vim.g would fail...

I'm using neovim 0.4.4

**Comment by b3nj5m1n** [comment]
You need at least version 0.5 for lua support in nvim.
