### ISSUE TITLE
Support for <count>gcc?

### ISSUE THREAD

**Issue by jaywonchung** [b3nj5m1n/kommentary#39]
Hi! Thanks for the great plugin.

I'm tried to transition from vim-commentary to kommentary, but it seems that kommentary is missing support for `<count>gcc`. For instance, `3gcc` toggles comments for three lines including the current line, just like how `3dd` deletes three lines.

Would you consider supporting this? Or, does it already have this and I failed to find it?

Thanks again.

**Comment by b3nj5m1n** [comment]
gcc toggles the current line, gc acts on a motion. If you want to comment 3 lines down, press 3gcj.

**Comment by jaywonchung** [comment]
Yes, I am aware of that. Supporting 3gcc would be duplicate, but will allow users of vim-commentary to migrate to kommentary more smoothly (if you are interested in facilitating this). I think this is all up to the owner, but I advocate support.

**Comment by b3nj5m1n** [comment]
Sorry but I don't really see a good reason to use this over normal motions. If you really need it for some reason you could always define your own mapping for it.
