### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by Chaitanyabsprip** [b3nj5m1n/kommentary#4]
I build the documentation but couldn't follow a single thing. The documentation mentions the functions and explains them but doesn't talk about configuration on user end. I couldn't figure out how to set it up yet.

**Comment by b3nj5m1n** [comment]
To use it, you just have to install the plugin using any plugin manager. See the install section in the README.

If you want to hack on it, or contribute, then the documentation you can build is useful, but not so much for end users.

**Comment by Chaitanyabsprip** [comment]
I have installed it. I also have vim-commentary installed. The documentation mentions something about `gc` being the prefix bind and right now I am not sure whether kommentary is working or vim-commentary is working. Also how to use this?

**Comment by b3nj5m1n** [comment]
Since this is a drop-in replacement for vim-commentary, you should uninstall that.

**Comment by Mte90** [comment]
I agree it is not clear the hotkeys as example I had to check the code.

I don't use vim-commentary but https://github.com/preservim/nerdcommenter so to me wasn't clear how to use it.

**Comment by b3nj5m1n** [comment]
> I agree it is not clear the hotkeys as example I had to check the code.

True, I apologize, I actually hadn't considered that someone would use this who isn't coming from vim-commentary, where these are the default bindings. I'll add a getting started section to the README with a list of the default keybindings.

**Comment by Chaitanyabsprip** [comment]
I removed vim-commentary and now kommentary is the only commenting plugin I have, however I cannot comment lines with `gcc`

**Comment by Chaitanyabsprip** [comment]
> > I agree it is not clear the hotkeys as example I had to check the code.
> 
> True, I apologize, I actually hadn't considered that someone would use this who isn't coming from vim-commentary, where these are the default bindings. I'll add a getting started section to the README with a list of the default keybindings.

Also add the list of languages that the plugin already supports

**Comment by b3nj5m1n** [comment]
> Also add the list of languages that the plugin already supports

It has basic support for every language for which commentstring is defined, and maintaining a list of all properly-supported languages would be a waste of time.

> I removed vim-commentary and now kommentary is the only commenting plugin I have, however I cannot comment lines with gcc

Are you getting an error message? If so, what does it say? If not, please make sure you're on the latest version of neovim () and have the latest version of this plugin installed. If it still doesn't work, please provide a minimal vimrc demonstrating your problem.

**Comment by Chaitanyabsprip** [comment]
for some reason sourcing my config was not enough, after a restart its working great.
