### ISSUE TITLE
Multi filetype files supporting

### ISSUE THREAD

**Issue by timsofteng** [b3nj5m1n/kommentary#40]
Hello. Does your plugin can recognise somehow inner filetype of complex files as .vue, .tsx, .html? Based on something... I dunno, maybe on treesitter.

**Comment by b3nj5m1n** [comment]
No, this has been discussed several times before and it's outside the scope of this plugin. Currently you have to use the context commentstring plugin.

See #37

**Comment by yutkat** [comment]
I use nvim-ts-context-commentstring and kommentary to deal with such cases.
https://github.com/b3nj5m1n/kommentary/issues/43
