### ISSUE TITLE
Repeat support

### ISSUE THREAD

**Issue by miladabc** [b3nj5m1n/kommentary#41]
Nice plugin, thanks for great work.
It seems that repeating with dot command does not work as it is in vim-commentary.
Do you have any plan for it?

**Comment by b3nj5m1n** [comment]
I had looked into that a few weeks ago, unfortunately it doesn't seem (neo)vim natively supports that.

I could make the plugin compatible with tpope's repeat plugin, I believe it was also a somewhat involved process when I looked into it, I'll have another look at it when I find the time. If you want, a pull request would be more than welcome.

**Comment by milad-abbasi** [comment]
Maybe [vim-repeat](https://github.com/tpope/vim-repeat) can help?

**Comment by cloggier** [comment]
@b3nj5m1n Perhaps that could be off help: https://github.com/nvim-treesitter/nvim-treesitter-textobjects/pull/52

**Comment by b3nj5m1n** [comment]
This is implemented with #71.
