### ISSUE TITLE
Comment or uncomment [count] lines.

### ISSUE THREAD

**Issue by horseinthesky** [b3nj5m1n/kommentary#42]
Hi.
Great plugin. Especially great to have the same mappings as vim-commentary.

But the most used (by myself) feature is absent
```
gcc                     Comment or uncomment [count] lines.
```

I still can do `gc5j` to comment the current line and 4 lines below but would be great to have good old `5gcc` to do it.

**Comment by b3nj5m1n** [comment]
Duplicate of #39.
