### ISSUE TITLE
Generalize to not rely on <Plug>

### ISSUE THREAD

**Issue by jc00ke** [b3nj5m1n/kommentary#46]
Hi, great plugin! I'm using `paq` and I'm having a hard time remapping the keys. I'm not sure if that's because the implementation relies on `<Plug>` or if it's something else.

```lua
vim.g.kommentary_create_default_mappings = false
paq 'b3nj5m1n/kommentary'

map("n", "<leader>cc",  "<Plug>kommentary_line_default", {})
map("n", "<leader>c",   "<Plug>kommentary_motion_default", {})
map("v", "<leader>c",   "<Plug>kommentary_visual_default", {})
```

Really I'm looking for `<leader>cc` to comment and `<leader>cu` to uncomment (line and block)

Any help would be greatly appreciated!

**Comment by b3nj5m1n** [comment]
What have you tried so far that hasn't worked? I'm pretty sure <Plug> has nothing to do with your plugin manager.

**Comment by jc00ke** [comment]
False alarm...

```lua
local function map(mode, lhs, rhs, opts)
  local options = {noremap = true}
  if opts then options = vim.tbl_extend('force', options, opts) end
  vim.api.nvim_set_keymap(mode, lhs, rhs, options)
end

-- doesn't work because the `map` function defaults to noremap = true
map("n", "<leader>cc", "<Plug>kommentary_line_default", {}) 

-- works!
map("n", "<leader>cc", "<Plug>kommentary_line_default", { noremap = false }) 

```

**Comment by flosker** [comment]
Why can't this plugin work with `noremap` instead of `map`?
