### ISSUE TITLE
Nested comments

### ISSUE THREAD

**Issue by jghauser** [b3nj5m1n/kommentary#51]
Thanks for all your work on this plugin!

One thing I'm missing in the lua alternatives to tpope's plugin is how that plugin solved nested comments. This is especially relevant for the html comments that I use in my markdown files: `<!-- comment -->`. The problem occurs when you have a text such as: 

`This is a<!-- comment --> text.` 

When uncommenting this it becomes:

`<!--This is a<!-- comment --> text.-->` 

That's unexpected because the comment that begins at the beginning of the line now ends at the first `-->`.

Tpope's plugin solved that by converting the nested comments into `<1!-- comment --1>`. The text then becomes:

`<!--This is a<1!-- comment --1> text.-->`

This string could then of course be uncommented again as well (removing the 1s). I'm not sure if this affects languages other than markdown.

If you're interested in implementing this, you might also want to take a look at this [issue](https://github.com/tpope/vim-commentary/issues/65); apparently the way tpope solved it leads to some problems (though this has never affected me).

**Comment by b3nj5m1n** [comment]
Couldn't you use the same mapping for kommentary?

**Comment by jghauser** [comment]
I'm sorry, I don't quite follow. What mapping are you referring to?

**Comment by b3nj5m1n** [comment]
Sorry, I should have been more clear, I meant the snippet posted in the issue you linked to.
```viml
augroup Xml
command! ValidComment execute "normal! mtvat\<esc>`<:'<,'>s/<1!--/<1!__/ge\<cr>:'<,'>s/--1>/__1>/ge\<cr>:nohlsearch\<cr>"
command! ValidUncomment execute "normal! mtvat\<esc>`<:'<,'>s/<1!__/<!--/ge\<cr>:'<,'>s/__1>/-->/ge\<cr>:nohlsearch\<cr>"
nnoremap <leader>vc :ValidComment<cr>
nnoremap <leader>vu :ValidUncomment<cr>
augroup END
```

**Comment by jghauser** [comment]
Thanks for the clarification!

As far as I can tell that command just fixes the problem discussed in that issue, namely the problem that the `<1!-- --1>` syntax causes issues in xml files. But my problem is that I don't even get the `<1-- --1>`. When I comment a line with pre-existing inline comments, these don't change at all, and that causes the problem discussed in my first post.

**Comment by b3nj5m1n** [comment]
Unfortunately, I don't think I will add this into the main plugin any time soon, so you'll probably have to implement a workaround yourself.

I think you should just be able to run a function to substitute the comments before running the comment function, here's a small test I did:
```lua
function hook()
    vim.cmd([[%s/<!--\(.*\)-->/<1!--\1--1>/g]])
end
```
If you have the following text:
```
This is a <!-- comment --> text.
```
And run `:lua hook()`, the text will turn into this:
```
This is a <1!-- comment --1> text.
```

**Comment by b3nj5m1n** [comment]
I hope my workaround solved the issue for you, unfortunately I'll not add any new features to kommentary, so I'll go ahead and close this issue.
