### ISSUE TITLE
Option to enable/disable space between comment character and code

### ISSUE THREAD

**Issue by mroavi** [b3nj5m1n/kommentary#54]
tpope's commentary plugin allows using the `b:commentary_format` to control the space between comment character(s) and code, e.g.:
```vim
" No space between comment character and code
let b:commentary_format = '#%s'
```
Is there a way to achieve the same with kommentary?

**Comment by adrian5** [comment]
I'd like this too. It's useful for differentiating between disabled code and actual comments.

**Comment by b3nj5m1n** [comment]
Hi, thanks for your interest in kommentary, unfortunately I'll not be adding any new features, I'm sorry I never got to this issue.
