### ISSUE TITLE
how to comment single line as a multile line?

### ISSUE THREAD

**Issue by shaeinst** [b3nj5m1n/kommentary#56]
for example
```cpp

int main() { 
     /* std::cout << "Hello World\n";  */
}
```
and if i select multiple lines, it should comment as
```cpp

int main() { 
     /* std::cout << "Hello World\n";  */
     /* ... */
     /* return 0; */

}
```

**Comment by captainko** [comment]
Yeah I have this problem too. I have to switch back to vim-commentary because of this  :cry:

**Comment by b3nj5m1n** [comment]
Hi, thanks for your interest in kommentary, unfortunately I'll not be adding any new features, I'm sorry I never got to this issue.
