### ISSUE TITLE
Why can't this plugin work with `noremap`?

### ISSUE THREAD

**Issue by flosker** [b3nj5m1n/kommentary#57]
This plugin doesn't work with `noremap = true`, why is that?

**Comment by Iron-E** [comment]
The examples from the README use `<Plug>`, which doesn't work with `noremap` because it is technically a mapping as well. Using `noremap` prevents expanding the `<Plug>` mapping, which is necessary for function

For more, see `:h using-<Plug>`

**Comment by flosker** [comment]
Ah! Thanks, I didn't know that ;)
