### ISSUE TITLE
Return to normal mode after commenting in visual mode

### ISSUE THREAD

**Issue by mroavi** [b3nj5m1n/kommentary#58]
Most commands in vim, when run in visual mode, return to normal mode after the command is completed. This is not the case with kommentary, which contrasts with tpope's commentary plugin. Could you consider changing this so that commenting out lines in visual mode automatically makes the editor return to normal mode?

**Comment by Iron-E** [comment]
You can use `<Plug>kommentary_visual_default<Esc>` as the visual mode mapping. It just presses `<Esc>` for you after using visual `<Plug>` mapping.

**Comment by mroavi** [comment]
Ahh, thanks. That's a quick walkaround. However, don't you think that this should be de default, like in vim-commentary?

**Comment by Iron-E** [comment]
Personally, yeah. I don't think the function itself should be changed, maybe just the docs since it would be easier for users to remove the `<Esc>` if we don't want it.

**Comment by mroavi** [comment]
Ok. So I'll leave this issue open for now to see what the repo owner thinks.

**Comment by mroavi** [comment]
and perhaps relevant to mention is that vim offers `gv` which can be used to start visual mode with the same area as the previous selection.

**Comment by b3nj5m1n** [comment]
I'm going to close this in favour of #49.
