### ISSUE TITLE
Performance issues with multi-single comments on long ranges

### ISSUE THREAD

**Issue by b3nj5m1n** [b3nj5m1n/kommentary#6]
When commenting in a range using single-comment style, so like this, but on hundreds or thousands of lines:
```lua
-- local function example()
    -- print("Example")
-- end
```
There's a performance issue because the function responsible for this action (`comment_in_range_single`) works by calling `comment_in_line` on every line of the range, because of that the folds are recomputed for every line.

Instead, we should have that function comment in every line in the range itself, then set the whole range once at the end using `nvim_buf_set_lines`.

See also #3 and #5.

**Comment by b3nj5m1n** [comment]
Implemented in 97d3e98a80b3413aed535cfdb777d417267aa508.

@kristijanhusak since you reported this, could you also test this out and let me know if you get a drastic improvement as well? I went from several seconds on a ~3000 lines file to ~ a fraction of a second.

Be aware that right now, the default mapping for gc in visual mode is for the default function toggling with multi line comments, not the one that comments out with single-line comments. So you would have to do that manually: `vmap gc     <Plug>kommentary_visual_singles`.

Feel free to reopen this issue if you encounter any bugs.

**Comment by kristijanhusak** [comment]
@b3nj5m1n works great, thanks!
