### ISSUE TITLE
Moving to beginning of next line

### ISSUE THREAD

**Issue by spamwax** [b3nj5m1n/kommentary#68]
Thanks for this plugin 🙏 

Is it possible to move to beginning of next line when after commenting a single line in normal mode?

**Comment by pernambucano** [comment]
complementing this issue, is there a way to configure the plugin to not make the next line a comment if we open it using `o` in normal mode?

**Comment by b3nj5m1n** [comment]
@spamwax This is not something in the main plugin, however you can write your own function to accomplish this.

@pernambucano This is not something kommentary does, it's a feature of vim itself. [Here](https://vim.fandom.com/wiki/Disable_automatic_comment_insertion) is a relevant article.
