### ISSUE TITLE
Embedded lua code in init.vim doesn't use right comment string

### ISSUE THREAD

**Issue by gerazov** [b3nj5m1n/kommentary#72]
Awesome plugin - I especially like commenting with motions!  :sunglasses:

I don't get the right commenting for embedded lua in my init.vim file, i.e. it inserts the `"` vim comment string:

![kommentary_luainvim](https://user-images.githubusercontent.com/15214418/142426922-60248c22-c1df-4094-8804-6b136f76f7a3.gif)

**Comment by b3nj5m1n** [comment]
Hi, context dependent comment strings aren't handled by this plugin, I suggest you take a look at [this plugin](https://github.com/JoosepAlviste/nvim-ts-context-commentstring#kommentary).

**Comment by gerazov** [comment]
Oh I see. Maybe document this in the README as it's an important feature for commenting ...

I still can't make it work. I added a lua part in the conf but it doesn't do the trick ...
```lua
require'nvim-treesitter.configs'.setup {
  context_commentstring = {
    enable = true,
    enable_autocmd = false,
  }
}
require('kommentary.config').configure_language("default", {
    prefer_single_line_comments = true,
    use_consistent_indentation = true,
})
require('kommentary.config').configure_language('typescriptreact', {
  single_line_comment_string = 'auto',
  multi_line_comment_strings = 'auto',
  hook_function = function()
    require('ts_context_commentstring.internal').update_commentstring()
  end,
})
require('kommentary.config').configure_language('lua', {
  single_line_comment_string = 'auto',
  multi_line_comment_strings = 'auto',
  hook_function = function()
    require('ts_context_commentstring.internal').update_commentstring()
  end,
})

```
