### ISSUE TITLE
prefer_single_line_comments as default for all languages

### ISSUE THREAD

**Issue by theduke** [b3nj5m1n/kommentary#75]
I'd like to use `prefer_single_line_comments` as the default for all languages, and only use multi-line comments for a few select ones. (`html`, `xml`, ...).

It would be nice if there was a global default setting that is used when no global setting is active.

**Comment by strange** [comment]
Doesn't the following from the README work?

```
require('kommentary.config').configure_language("default", {
    prefer_single_line_comments = true,
})
```

**Comment by theduke** [comment]
Ah yes, that works indeed.
