### ISSUE TITLE
Expose Lua API directly

### ISSUE THREAD

**Issue by mrjones2014** [b3nj5m1n/kommentary#80]
Now that we have `vim.keymap.set` API in Neovim nightly, it allows us to setup keymaps in really clean ways.

I'm using [legendary.nvim](https://github.com/mrjones2014/legendary.nvim) to set all my keymaps, and I try to keep them all in the same place. I tend to have plugins not set their own keymaps through the plugin config, and instead set the keymaps in my single location where I set up all my keymaps.

You can also now set keymaps directly to Lua functions.

Can you expose the implementations of the `<Plug>` mappings as Lua functions I can map from my keymaps file?

**Comment by declancm** [comment]
I'm not sure if this is what you are wanting but I use the following function (found at the bottom of 'lua/kommentary/init.lua') for my custom keymaps:
```lua
require('kommentary').toggle_comment(arg1, arg2)
```
Arg1 is the first line you want commented and arg2 is the last. For example, to toggle comments on the current line I use:
```lua
require('kommentary').toggle_comment(vim.fn.line('.'), vim.fn.line('.'))
```
And to comment lines 69 to 420 would be:
```lua
require('kommentary').toggle_comment(69, 420)
```
I hope this helped!

**Comment by b3nj5m1n** [comment]
Hi, thanks for your interest in kommentary, unfortunately I'll not be adding any new features, I'm sorry I never got to this issue.
