### ISSUE TITLE
[FR] add one universal command to uncomment

### ISSUE THREAD

**Issue by glyh** [b3nj5m1n/kommentary#82]
As title, sometimes it would be handy if there's such command.

For example:
```lua
  a = 1
  --[[ b = 2
  c = 3
  d = 4]]
```
normally you would have to select the 3 lines and toggle comments, but it would be better if this plugin can detect the comment under cursor.

**Comment by b3nj5m1n** [comment]
As I said in the other issue of yours, I won't be adding any more features, sorry I never got to this one.

If you're still using kommentary and want this functionality, you should be able to implement it yourself using https://github.com/b3nj5m1n/kommentary#advanced-configuration.
